# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Natak API - Build and Deploy

on:
  push:
    branches: ["main", "dev"]

env:
  AZURE_WEBAPP_PACKAGE_PATH: "publish"
  ARTIFACT_NAME: "publish-artifact"
  ARTIFACT_PATH: "./artifact"
  IMAGE_NAME: "${{ secrets.DOCKER_USERNAME }}/natak-api"
  TAG: "${{ github.ref == 'refs/head/main' && 'latest' || 'dev' }}"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Natak

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --verbosity normal

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Natak

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Log in to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/arm/v7 -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

  deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.RASPBERRY_PI_IP }}
          username: ${{ secrets.RASPBERRY_PI_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd NatakAPI
            docker pull $IMAGE_NAME:$TAG
            docker-compose -f ~/compose.yml up -d
