# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy to Azure

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Catan

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set up dependency caching for faster builds
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Test
      run: dotnet test --verbosity normal

    - name: Build (Release)
      run: dotnet build Catan.sln --no-restore --configuration Release

    - name: Publish the project
      run: dotnet publish Catan.API/Catan.API.csproj -c Release -o ./publish
      
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to dev
      if: github.ref == 'refs/heads/dev'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_DEV_WEB_APP_NAME }}
        package: ./publish
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        
    - name: Deploy to prod
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_DEV_WEB_APP_NAME }}
        package: ./publish
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
    
    - name: Logout
      run: |
        az logout
